export const mockAnswers = [
  {
    id: 1,
    title: 'Для изменения типа и величины проводимости кремниевой подложки',
    isCorrect: true,
    questionId: 1,
  },
  {
    id: 2,
    title: 'для повышения твердости и износостойкости кремниевой подложки',
    isCorrect: false,
    questionId: 1,
  },
  {
    id: 3,
    title: 'для изменения гидрофильных и гидрофобных свойств поверхности подложки',
    isCorrect: false,
    questionId: 1,
  },
  {
    id: 4,
    title: 'для повешения прочности кремниевой подложки',
    isCorrect: false,
    questionId: 1,
  },
  {
    id: 5,
    title: 'для изменения толщины подожки',
    isCorrect: false,
    questionId: 1,
  },
  {
    id: 6,
    title: 'двумя законами Фика',
    isCorrect: true,
    questionId: 2,
  },
  {
    id: 7,
    title: 'тремя уравнениями формируемых потоков окислителя',
    isCorrect: false,
    questionId: 2,
  },
  {
    id: 8,
    title: 'пятью уравнениями формируемых восходящих потоков',
    isCorrect: false,
    questionId: 2,
  },
  {
    id: 9,
    title: 'двумя уравнениями формируемых потоков водорода',
    isCorrect: false,
    questionId: 2,
  },
  {
    id: 10,
    title: 'одним уравнением формируемого потока газа',
    isCorrect: false,
    questionId: 2,
  },
  {
    id: 11,
    title: 'газообразном',
    isCorrect: true,
    questionId: 3,
  },
  {
    id: 12,
    title: 'жидком',
    isCorrect: false,
    questionId: 3,
  },
  {
    id: 13,
    title: 'твердом',
    isCorrect: false,
    questionId: 3,
  },
  {
    id: 14,
    title: 'золь-гель',
    isCorrect: false,
    questionId: 3,
  },
  {
    id: 15,
    title: 'расплав',
    isCorrect: false,
    questionId: 3,
  },
  {
    id: 16,
    title: 'фосфор, мышьяк, сурьма',
    isCorrect: true,
    questionId: 4,
  },
  {
    id: 17,
    title: 'бор, алюминий, оксид кремния',
    isCorrect: false,
    questionId: 4,
  },
  {
    id: 18,
    title: 'бор, фосфор, германий',
    isCorrect: false,
    questionId: 4,
  },
  {
    id: 19,
    title: 'фосфор, азот, моносилан',
    isCorrect: false,
    questionId: 4,
  },
  {
    id: 20,
    title: 'дихлорсилан и моносилан',
    isCorrect: false,
    questionId: 4,
  },
  {
    id: 21,
    title: 'алюминий, медь, оксид кремния',
    isCorrect: true,
    questionId: 5,
  },
  {
    id: 22,
    title: 'фосфор, мышьяк, сурьма',
    isCorrect: false,
    questionId: 5,
  },
  {
    id: 23,
    title: 'аммиак, азот, моносилан',
    isCorrect: false,
    questionId: 5,
  },
  {
    id: 24,
    title: 'дихлорсилан и моносилан',
    isCorrect: false,
    questionId: 5,
  },
  {
    id: 25,
    title: 'арсин (AsH 3 ), фосфин (PH 3 ) диборанe (B 2 H 6 ), стибин (SbH 3 )',
    isCorrect: true,
    questionId: 6,
  },
  {
    id: 26,
    title: 'аммиак (NH 3 ), фосфин (PH 3 ), арсин (AsH 3 )',
    isCorrect: false,
    questionId: 6,
  },
  {
    id: 27,
    title: 'гексафторид вольфрама (WF 6 ), диборанe (B 2 H 6 )',
    isCorrect: false,
    questionId: 6,
  },
  {
    id: 28,
    title: 'моносилан (SiH 4 ), дихлорсилан (H 2 SiCl 2 )',
    isCorrect: false,
    questionId: 6,
  },
  {
    id: 29,
    title: 'гексафторид ванадия (VF 6 ), хладон 14 (CF 4 ), элегаз (SF 6 )',
    isCorrect: false,
    questionId: 6,
  },
  {
    id: 30,
    title: 'двухстадийное легирование: загонка и разгонка',
    isCorrect: true,
    questionId: 7,
  },
  {
    id: 31,
    title: 'одностадийное легирование из неограниченного источника',
    isCorrect: false,
    questionId: 7,
  },
  {
    id: 32,
    title: 'двухстадийное легирование: возгонка и загонка',
    isCorrect: false,
    questionId: 7,
  },
  {
    id: 33,
    title: 'одностадийное легирование из ограниченного источника',
    isCorrect: false,
    questionId: 7,
  },
  {
    id: 34,
    title: 'трехстадийное легирование: возгонка, загонка и разгонка',
    isCorrect: false,
    questionId: 7,
  },
  {
    id: 35,
    title: 'да',
    isCorrect: true,
    questionId: 8,
  },
  {
    id: 36,
    title: 'нет',
    isCorrect: false,
    questionId: 8,
  },
  {
    id: 37,
    title: 'иногда',
    isCorrect: false,
    questionId: 8,
  },
  {
    id: 38,
    title: 'при комнатной температуре',
    isCorrect: false,
    questionId: 8,
  },
  {
    id: 39,
    title: 'при охлаждении',
    isCorrect: false,
    questionId: 8,
  },
  {
    id: 40,
    title: 'нет никогда',
    isCorrect: true,
    questionId: 9,
  },
  {
    id: 41,
    title: 'есть всегда',
    isCorrect: false,
    questionId: 9,
  },
  {
    id: 42,
    title: 'возможно при особых условиях',
    isCorrect: false,
    questionId: 9,
  },
  {
    id: 43,
    title: 'есть при нагреве',
    isCorrect: false,
    questionId: 9,
  },
  {
    id: 44,
    title: 'есть в аморфных материалах',
    isCorrect: false,
    questionId: 9,
  },
  {
    id: 45,
    title: 'скорость',
    isCorrect: false,
    questionId: 10,
  },
  {
    id: 46,
    title: 'анизотропия',
    isCorrect: false,
    questionId: 10,
  },
  {
    id: 47,
    title: 'селективность',
    isCorrect: false,
    questionId: 10,
  },
  {
    id: 48,
    title: 'инертность',
    isCorrect: true,
    questionId: 10,
  },
  {
    id: 49,
    title: 'горизонтально ее поверхности',
    isCorrect: false,
    questionId: 11,
  },
  {
    id: 50,
    title: 'перпендикулярно ее поверхности',
    isCorrect: true,
    questionId: 11,
  },
  {
    id: 51,
    title: 'по всем направлениям от ее поверхности',
    isCorrect: false,
    questionId: 11,
  },
  {
    id: 52,
    title: 'локально на участке ее поверхности',
    isCorrect: false,
    questionId: 11,
  },
  {
    id: 53,
    title: 'селективность',
    isCorrect: true,
    questionId: 12,
  },
  {
    id: 54,
    title: 'воспроизводимость',
    isCorrect: false,
    questionId: 12,
  },
  {
    id: 55,
    title: 'загрузочный эффект',
    isCorrect: false,
    questionId: 12,
  },
  {
    id: 56,
    title: 'локализация',
    isCorrect: false,
    questionId: 12,
  },
  {
    id: 57,
    title: 'насыщения',
    isCorrect: false,
    questionId: 13,
  },
  {
    id: 58,
    title: 'нейтральности',
    isCorrect: false,
    questionId: 13,
  },
  {
    id: 59,
    title: 'обеднения',
    isCorrect: true,
    questionId: 13,
  },
  {
    id: 60,
    title: 'кислотности',
    isCorrect: false,
    questionId: 13,
  },
  {
    id: 61,
    title: 'точно повторяет размер отверстия в маске',
    isCorrect: false,
    questionId: 14,
  },
  {
    id: 62,
    title: 'простирается за границы отверстия в маске',
    isCorrect: true,
    questionId: 14,
  },
  {
    id: 63,
    title: 'оказывается меньше отверстия в маске',
    isCorrect: false,
    questionId: 14,
  },
  {
    id: 64,
    title: 'оказывается меньше отверстия в маске',
    isCorrect: false,
    questionId: 14,
  },
  {
    id: 65,
    title: 'увеличивают',
    isCorrect: false,
    questionId: 15,
  },
  {
    id: 66,
    title: 'не изменяют',
    isCorrect: false,
    questionId: 15,
  },
  {
    id: 67,
    title: 'уменьшают',
    isCorrect: true,
    questionId: 15,
  },
  {
    id: 68,
    title: 'делают эллипсообразным',
    isCorrect: false,
    questionId: 15,
  },
  {
    id: 69,
    title: 'выбором травящих компонентов',
    isCorrect: false,
    questionId: 16,
  },
  {
    id: 70,
    title: 'толщиной пленки, лежащей под маской',
    isCorrect: true,
    questionId: 16,
  },
  {
    id: 71,
    title: 'размером окон для травления',
    isCorrect: false,
    questionId: 16,
  },
  {
    id: 72,
    title: 'субатомными величинами',
    isCorrect: false,
    questionId: 16,
  },
  {
    id: 73,
    title: 'химическое травление',
    isCorrect: false,
    questionId: 17,
  },
  {
    id: 74,
    title: 'изотропное травление',
    isCorrect: false,
    questionId: 17,
  },
  {
    id: 75,
    title: 'анизотропное травление',
    isCorrect: true,
    questionId: 17,
  },
  {
    id: 76,
    title: 'адиабатическое травление',
    isCorrect: false,
    questionId: 17,
  },
  {
    id: 77,
    title: 'изотропными травителями',
    isCorrect: true,
    questionId: 18,
  },
  {
    id: 78,
    title: 'анизотропными травителями',
    isCorrect: false,
    questionId: 18,
  },
  {
    id: 79,
    title: 'адиабатическими травителями',
    isCorrect: false,
    questionId: 18,
  },
  {
    id: 80,
    title: 'методом скрайбирования',
    isCorrect: false,
    questionId: 18,
  },
  {
    id: 81,
    title: 'адиабатические травители',
    isCorrect: false,
    questionId: 19,
  },
  {
    id: 82,
    title: 'изотропные травители',
    isCorrect: true,
    questionId: 19,
  },
  {
    id: 83,
    title: 'анизотропные травители',
    isCorrect: false,
    questionId: 19,
  },
  {
    id: 84,
    title: 'химические травители',
    isCorrect: false,
    questionId: 19,
  },
  {
    id: 85,
    title: 'методом центрифугирования из-за большой массы напыленного металла',
    isCorrect: false,
    questionId: 20,
  },
  {
    id: 86,
    title: 'ионно-плазменной бомбардировкой',
    isCorrect: false,
    questionId: 20,
  },
  {
    id: 87,
    title: 'методом скрайбирования',
    isCorrect: false,
    questionId: 20,
  },
  {
    id: 88,
    title: 'с помощью растворителя методом взрывной литографии',
    isCorrect: true,
    questionId: 20,
  },
  {
    id: 89,
    title: 'изотропное травление',
    isCorrect: true,
    questionId: 21,
  },
  {
    id: 90,
    title: 'анизотропное травление',
    isCorrect: false,
    questionId: 21,
  },
  {
    id: 91,
    title: 'адиабатическое травление',
    isCorrect: false,
    questionId: 21,
  },
  {
    id: 92,
    title: 'скрайбирование ХМП',
    isCorrect: false,
    questionId: 21,
  },
  {
    id: 93,
    title:
      'увеличенмем давления выше определённого предела в следствии неидеальности гермитичности',
    isCorrect: false,
    questionId: 22,
  },
  {
    id: 94,
    title: 'селективностью изотропных травителей',
    isCorrect: false,
    questionId: 22,
  },
  {
    id: 95,
    title: 'истощением активного травителя вследствие взаимодействия с подложкой',
    isCorrect: true,
    questionId: 22,
  },
  {
    id: 96,
    title:
      'малой площадью поверхности из-за постепенного выравнивания рельефа в следствии травления',
    isCorrect: false,
    questionId: 22,
  },
  {
    id: 97,
    title: 'анализ отходов травления',
    isCorrect: false,
    questionId: 23,
  },
  {
    id: 98,
    title: 'скорость газификации поверхности с помощью радикалов при отсутствии плазмы',
    isCorrect: true,
    questionId: 23,
  },
  {
    id: 99,
    title: 'визуальное наблюдение электронным микроскопом',
    isCorrect: false,
    questionId: 23,
  },
  {
    id: 100,
    title: 'температура процесса',
    isCorrect: false,
    questionId: 23,
  },
  {
    id: 101,
    title: '1:1 и 2:1',
    isCorrect: false,
    questionId: 24,
  },
  {
    id: 102,
    title: '11:1 и 6:1',
    isCorrect: false,
    questionId: 24,
  },
  {
    id: 103,
    title: '36:1 и 41:1',
    isCorrect: false,
    questionId: 24,
  },
  {
    id: 104,
    title: '41:1 и 26:1',
    isCorrect: true,
    questionId: 24,
  },
  {
    id: 105,
    title: 'диэлектрические травители',
    isCorrect: false,
    questionId: 25,
  },
  {
    id: 106,
    title: 'изотропные травители',
    isCorrect: true,
    questionId: 25,
  },
  {
    id: 107,
    title: 'анизотропные травители',
    isCorrect: false,
    questionId: 25,
  },
  {
    id: 108,
    title: 'скрайбирование',
    isCorrect: false,
    questionId: 25,
  },
  {
    id: 109,
    title:
      'увеличением давления выше определённого предела в следствии неидеальности герметичности',
    isCorrect: false,
    questionId: 26,
  },
  {
    id: 110,
    title:
      'уменьшение площади обрабатываемой поверхности и увеличение концентрация активных веществ',
    isCorrect: true,
    questionId: 26,
  },
  {
    id: 111,
    title: 'селективностью изотропных травителей',
    isCorrect: false,
    questionId: 26,
  },
  {
    id: 112,
    title:
      'малой площадью поверхности из-за постепенного выравнивания рельефа в следствии травления',
    isCorrect: false,
    questionId: 26,
  },
  {
    id: 113,
    title: 'концентрацией травителя',
    isCorrect: false,
    questionId: 27,
  },
  {
    id: 114,
    title: 'диффузией',
    isCorrect: true,
    questionId: 27,
  },
  {
    id: 115,
    title: 'тепрературой',
    isCorrect: false,
    questionId: 27,
  },
  {
    id: 116,
    title: 'на перенос травителя из объема плазмы к поверхности ничего не влияет',
    isCorrect: false,
    questionId: 27,
  },
  {
    id: 117,
    title: 'размеры элементов рельефа',
    isCorrect: false,
    questionId: 28,
  },
  {
    id: 118,
    title: 'плотность элементов рельефа',
    isCorrect: false,
    questionId: 28,
  },
  {
    id: 119,
    title: 'размеры и плотность элементов рельефа',
    isCorrect: true,
    questionId: 28,
  },
  {
    id: 120,
    title: 'температура',
    isCorrect: false,
    questionId: 28,
  },
  {
    id: 121,
    title: 'металла',
    isCorrect: false,
    questionId: 29,
  },
  {
    id: 122,
    title: 'соли металла',
    isCorrect: false,
    questionId: 29,
  },
  {
    id: 123,
    title: 'кремния',
    isCorrect: false,
    questionId: 29,
  },
  {
    id: 124,
    title: 'оксида кремния',
    isCorrect: true,
    questionId: 29,
  },
  {
    id: 125,
    title: 'сохраняет её гладкой',
    isCorrect: true,
    questionId: 30,
  },
  {
    id: 126,
    title: 'ведет к появлению микроскопических неровностей поверхности',
    isCorrect: false,
    questionId: 30,
  },
  {
    id: 127,
    title: 'травит с высокой скоростью',
    isCorrect: false,
    questionId: 30,
  },
  {
    id: 128,
    title: 'перестаёт реагировать',
    isCorrect: false,
    questionId: 30,
  },
  {
    id: 129,
    title: 'физическое распыление',
    isCorrect: true,
    questionId: 31,
  },
  {
    id: 130,
    title: 'химическое травление',
    isCorrect: false,
    questionId: 31,
  },
  {
    id: 131,
    title: 'адиабатическое травление',
    isCorrect: false,
    questionId: 31,
  },
  {
    id: 132,
    title: 'скрайбирование',
    isCorrect: false,
    questionId: 31,
  },
  {
    id: 133,
    title: 'пороговыми значениями коэффициента плавления материалов',
    isCorrect: false,
    questionId: 32,
  },
  {
    id: 134,
    title: 'пороговыми значениями коэффициента кристаллизации материалов',
    isCorrect: false,
    questionId: 32,
  },
  {
    id: 135,
    title: 'пороговыми значениями коэффициента распыления материалов',
    isCorrect: true,
    questionId: 32,
  },
  {
    id: 136,
    title: 'мощностью установки',
    isCorrect: false,
    questionId: 32,
  },
  {
    id: 137,
    title: '3 – 30 эВ',
    isCorrect: false,
    questionId: 33,
  },
  {
    id: 138,
    title: '≤30 эВ',
    isCorrect: false,
    questionId: 33,
  },
  {
    id: 139,
    title: '50 - 100 эВ',
    isCorrect: false,
    questionId: 33,
  },
  {
    id: 140,
    title: '≥100 эВ',
    isCorrect: true,
    questionId: 33,
  },
  {
    id: 141,
    title: 'источником напыления и травления',
    isCorrect: false,
    questionId: 34,
  },
  {
    id: 142,
    title: 'только источником травителя',
    isCorrect: true,
    questionId: 34,
  },
  {
    id: 143,
    title: 'только источником напыления',
    isCorrect: false,
    questionId: 34,
  },
  {
    id: 144,
    title: 'с такой энергией ионов плазма не горит',
    isCorrect: false,
    questionId: 34,
  },
  {
    id: 145,
    title: 'эффект птичий клюв',
    isCorrect: false,
    questionId: 35,
  },
  {
    id: 146,
    title: 'нарастание стенок',
    isCorrect: false,
    questionId: 35,
  },
  {
    id: 147,
    title: 'расглаживание поверхности',
    isCorrect: false,
    questionId: 35,
  },
  {
    id: 148,
    title: 'подтравливание',
    isCorrect: true,
    questionId: 35,
  },
  {
    id: 149,
    title: 'для изменения типа и величины проводимости кремниевой подложки',
    isCorrect: true,
    questionId: 36,
  },
  {
    id: 150,
    title: 'для повышения твердости и износостойкости кремниевой подложки',
    isCorrect: false,
    questionId: 36,
  },
  {
    id: 151,
    title: 'для изменения гидрофильных и гидрофобных свойств поверхности подложки',
    isCorrect: false,
    questionId: 36,
  },
  {
    id: 152,
    title: 'для повешения прочности кремниевой подложки',
    isCorrect: false,
    questionId: 36,
  },
  {
    id: 153,
    title: 'для изменения толщины подожки',
    isCorrect: false,
    questionId: 36,
  },
  {
    id: 154,
    title: 'фосфор, мышьяк, сурьма',
    isCorrect: true,
    questionId: 37,
  },
  {
    id: 155,
    title: 'бор, алюминий, оксид кремния',
    isCorrect: false,
    questionId: 37,
  },
  {
    id: 156,
    title: 'бор, фосфор, германий',
    isCorrect: false,
    questionId: 37,
  },
  {
    id: 157,
    title: 'фосфор, азот, моносилан',
    isCorrect: false,
    questionId: 37,
  },
  {
    id: 158,
    title: 'дихлорсилан и моносилан',
    isCorrect: false,
    questionId: 37,
  },
  {
    id: 159,
    title: 'бор',
    isCorrect: true,
    questionId: 38,
  },
  {
    id: 160,
    title: 'алюминий, медь, оксид кремния',
    isCorrect: false,
    questionId: 38,
  },
  {
    id: 161,
    title: 'фосфор, мышьяк, сурьма',
    isCorrect: false,
    questionId: 38,
  },
  {
    id: 162,
    title: 'аммиак, азот, моносилан',
    isCorrect: false,
    questionId: 38,
  },
  {
    id: 163,
    title: 'дихлорсилан и моносилан',
    isCorrect: false,
    questionId: 38,
  },
  {
    id: 164,
    title: 'нет',
    isCorrect: true,
    questionId: 39,
  },
  {
    id: 165,
    title: 'да',
    isCorrect: false,
    questionId: 39,
  },
  {
    id: 166,
    title: 'иногда',
    isCorrect: false,
    questionId: 39,
  },
  {
    id: 167,
    title: 'при комнатной температуре',
    isCorrect: false,
    questionId: 39,
  },
  {
    id: 168,
    title: 'при охлаждении',
    isCorrect: false,
    questionId: 39,
  },
  {
    id: 169,
    title: 'есть – при изменении энергии ионов и дозы',
    isCorrect: true,
    questionId: 40,
  },
  {
    id: 170,
    title: 'нет никогда',
    isCorrect: false,
    questionId: 40,
  },
  {
    id: 171,
    title: 'есть при нагреве',
    isCorrect: false,
    questionId: 40,
  },
  {
    id: 172,
    title: 'возможно, при особых условиях',
    isCorrect: false,
    questionId: 40,
  },
  {
    id: 173,
    title: 'есть в поликристаллических материалах',
    isCorrect: false,
    questionId: 40,
  },
  {
    id: 174,
    title:
      'внедрение атомов примеси в полупроводниковую подложку методом ионной имплантации при комнатной температуре',
    isCorrect: true,
    questionId: 41,
  },
  {
    id: 175,
    title:
      'внедрение атомов примеси в полупроводниковую подложку за счет эффекта диффузии при комнатной температуре',
    isCorrect: false,
    questionId: 41,
  },
  {
    id: 176,
    title:
      'внедрение атомов примеси в полупроводниковую подложку за счет эффекта диффузии при температуре 1000°С',
    isCorrect: false,
    questionId: 41,
  },
  {
    id: 177,
    title:
      'внедрение атомов примеси в полупроводниковую подложку методом ионной имплантации при температуре 1000°С',
    isCorrect: false,
    questionId: 41,
  },
  {
    id: 178,
    title:
      'внедрение атомов примеси в полупроводниковую подложку методом электронно-лучевой обработки',
    isCorrect: false,
    questionId: 41,
  },
  {
    id: 179,
    title: 'энергией ионов в пучке',
    isCorrect: true,
    questionId: 42,
  },
  {
    id: 180,
    title: 'током ионного пучка',
    isCorrect: false,
    questionId: 42,
  },
  {
    id: 181,
    title: 'плотностью тока ионного пучка',
    isCorrect: false,
    questionId: 42,
  },
  {
    id: 182,
    title: 'дивергенцией ионного пучка',
    isCorrect: false,
    questionId: 42,
  },
  {
    id: 183,
    title: 'площадью сечения ионного пучка',
    isCorrect: false,
    questionId: 42,
  },
  {
    id: 184,
    title: 'при комнатной',
    isCorrect: false,
    questionId: 43,
  },
  {
    id: 185,
    title: 'при температуре плавления алюминия',
    isCorrect: false,
    questionId: 43,
  },
  {
    id: 186,
    title: 'при температуре 900-1250°С',
    isCorrect: false,
    questionId: 43,
  },
  {
    id: 187,
    title: 'при температуре абсолютного нуля',
    isCorrect: false,
    questionId: 43,
  },
  {
    id: 188,
    title: 'при температуре 50-250°С',
    isCorrect: false,
    questionId: 43,
  },
  {
    id: 189,
    title: 'плотностью тока ионного пучка за единицу времени – дозой',
    isCorrect: true,
    questionId: 44,
  },
  {
    id: 190,
    title: 'энергией ионов в пучке',
    isCorrect: false,
    questionId: 44,
  },
  {
    id: 191,
    title: 'током ионного пучка на единицу площади',
    isCorrect: false,
    questionId: 44,
  },
  {
    id: 192,
    title: 'дивергенцией ионного пучка на единицу его длины',
    isCorrect: false,
    questionId: 44,
  },
  {
    id: 193,
    title: 'формой сечения ионного пучка',
    isCorrect: false,
    questionId: 44,
  },
  {
    id: 194,
    title: 'увеличивает глубину проникновения ионов примеси в подложку',
    isCorrect: true,
    questionId: 45,
  },
  {
    id: 195,
    title: 'уменьшает глубину проникновения ионов примеси в подложку',
    isCorrect: false,
    questionId: 45,
  },
  {
    id: 196,
    title: 'увеличивает концентрацию ионов примеси у поверхности',
    isCorrect: false,
    questionId: 45,
  },
  {
    id: 197,
    title: 'увеличивает концентрацию ионов примеси под фоторезистивной маской',
    isCorrect: false,
    questionId: 45,
  },
  {
    id: 198,
    title: 'уменьшает повреждения кристаллической структуры подложки',
    isCorrect: false,
    questionId: 45,
  },
  {
    id: 199,
    title: '<110>',
    isCorrect: true,
    questionId: 46,
  },
  {
    id: 200,
    title: '<111>',
    isCorrect: false,
    questionId: 46,
  },
  {
    id: 201,
    title: '<100>',
    isCorrect: false,
    questionId: 46,
  },
  {
    id: 202,
    title: 'не важно',
    isCorrect: false,
    questionId: 46,
  },
  {
    id: 203,
    title: 'ориентация слабо влияет на эффект каналирования',
    isCorrect: false,
    questionId: 46,
  },
  {
    id: 204,
    title: 'разместить подложку под углом 5-7 градусов от нормали ионного пучка к поверхности',
    isCorrect: true,
    questionId: 47,
  },
  {
    id: 205,
    title: 'разместить под углом 45 градусов от нормали ионного пучка к поверхности',
    isCorrect: false,
    questionId: 47,
  },
  {
    id: 206,
    title: 'затормозить ионы перед столкновением с поверхностью',
    isCorrect: false,
    questionId: 47,
  },
  {
    id: 207,
    title: 'покрыть поверхность подложки толстым слоем оксида кремния',
    isCorrect: false,
    questionId: 47,
  },
  {
    id: 208,
    title: 'покрыть поверхность слоем металла',
    isCorrect: false,
    questionId: 47,
  },
  {
    id: 209,
    title: 'низких энергиях бомбардирующих ионов',
    isCorrect: true,
    questionId: 48,
  },
  {
    id: 210,
    title: 'больших энергиях бомбардирующих ионов',
    isCorrect: false,
    questionId: 48,
  },
  {
    id: 211,
    title: 'наличии в подложке элементов с большой атомной массой',
    isCorrect: false,
    questionId: 48,
  },
  {
    id: 212,
    title: 'наличии в подложке элементов с малой атомной массой',
    isCorrect: false,
    questionId: 48,
  },
  {
    id: 213,
    title: 'проявлении эффекта каналирования',
    isCorrect: false,
    questionId: 48,
  },
  {
    id: 214,
    title: 'сила Лоренца',
    isCorrect: true,
    questionId: 49,
  },
  {
    id: 215,
    title: 'сила Ван Дер Ваальса',
    isCorrect: false,
    questionId: 49,
  },
  {
    id: 216,
    title: 'сила упругости',
    isCorrect: false,
    questionId: 49,
  },
  {
    id: 217,
    title: 'сила Архимеда',
    isCorrect: false,
    questionId: 49,
  },
  {
    id: 218,
    title: 'сила тяжести',
    isCorrect: false,
    questionId: 49,
  },
  {
    id: 219,
    title: 'ускорения ионов',
    isCorrect: false,
    questionId: 50,
  },
  {
    id: 220,
    title: 'получения ионов',
    isCorrect: false,
    questionId: 50,
  },
  {
    id: 221,
    title: 'измерения плотности ионного тока',
    isCorrect: false,
    questionId: 50,
  },
  {
    id: 222,
    title: 'коллимации пучка ионов',
    isCorrect: false,
    questionId: 50,
  },
  {
    id: 223,
    title: 'сепарации ионов с заданным соотношением масса/заряд',
    isCorrect: true,
    questionId: 50,
  },
  {
    id: 224,
    title: 'активации атомов примеси и устранения дефектов кристаллической решетки подложки',
    isCorrect: true,
    questionId: 51,
  },
  {
    id: 225,
    title: 'повышения скорости диффузии атомов примеси и повышения глубины залегания p-n перехода',
    isCorrect: false,
    questionId: 51,
  },
  {
    id: 226,
    title: 'очистки поверхности подложки и «разгонки» примеси',
    isCorrect: false,
    questionId: 51,
  },
  {
    id: 227,
    title: 'снятия механических напряжений в подложке и удаления фоторезистивной маски',
    isCorrect: false,
    questionId: 51,
  },
  {
    id: 228,
    title: 'улучшения равномерности легирования и снижения «теневого» эффекта',
    isCorrect: false,
    questionId: 51,
  },
  {
    id: 229,
    title: 'для обеспечения групповой обработки подложек',
    isCorrect: true,
    questionId: 52,
  },
  {
    id: 230,
    title: 'для увеличения скорости ионов',
    isCorrect: false,
    questionId: 52,
  },
  {
    id: 231,
    title: 'для управления концентрации атомов примеси',
    isCorrect: false,
    questionId: 52,
  },
  {
    id: 232,
    title: 'для разгонки примесей от центра к краю подложки',
    isCorrect: false,
    questionId: 52,
  },
  {
    id: 233,
    title: 'для удобства имплантации',
    isCorrect: false,
    questionId: 52,
  },
  {
    id: 234,
    title: 'легкий',
    isCorrect: true,
    questionId: 53,
  },
  {
    id: 235,
    title: 'тяжелый',
    isCorrect: false,
    questionId: 53,
  },
  {
    id: 236,
    title: 'соразмерный кремнию',
    isCorrect: false,
    questionId: 53,
  },
  {
    id: 237,
    title: 'не важно',
    isCorrect: false,
    questionId: 53,
  },
  {
    id: 238,
    title: 'многозарядный',
    isCorrect: false,
    questionId: 53,
  },
  {
    id: 239,
    title: 'размещение атомов примеси в узлах кристаллической решетки',
    isCorrect: true,
    questionId: 54,
  },
  {
    id: 240,
    title: 'размещение атомов примеси в междоузлиях кристаллической решетки',
    isCorrect: false,
    questionId: 54,
  },
  {
    id: 241,
    title: 'аморфитизация структуры',
    isCorrect: false,
    questionId: 54,
  },
  {
    id: 242,
    title: 'образование химических соединений',
    isCorrect: false,
    questionId: 54,
  },
  {
    id: 243,
    title: 'повышение их потенциальной энергии',
    isCorrect: false,
    questionId: 54,
  },
  {
    id: 244,
    title: 'для исключения формирования дефекта неравномерного легирования',
    isCorrect: true,
    questionId: 55,
  },
  {
    id: 245,
    title: 'так исторически сложилось',
    isCorrect: false,
    questionId: 55,
  },
  {
    id: 246,
    title: 'для повышения глубины имплантации',
    isCorrect: false,
    questionId: 55,
  },
  {
    id: 247,
    title: 'для повышения подвижности носителей зарядов',
    isCorrect: false,
    questionId: 55,
  },
  {
    id: 248,
    title: 'для сохранения поверхностных свойств кремния',
    isCorrect: false,
    questionId: 55,
  },
  {
    id: 249,
    title: '900-1250°С',
    isCorrect: true,
    questionId: 67,
  },
  {
    id: 250,
    title: '50-350°С',
    isCorrect: false,
    questionId: 67,
  },
  {
    id: 251,
    title: '300-500°С',
    isCorrect: false,
    questionId: 67,
  },
  {
    id: 252,
    title: '500-850°С',
    isCorrect: false,
    questionId: 67,
  },
  {
    id: 253,
    title: '15-35°С',
    isCorrect: false,
    questionId: 67,
  },
  {
    id: 254,
    title: 'монокристаллические слои на монокристаллической подложке',
    isCorrect: true,
    questionId: 57,
  },
  {
    id: 255,
    title: 'аморфные пленки на монокристаллической подложке',
    isCorrect: false,
    questionId: 57,
  },
  {
    id: 256,
    title: 'поликристаллические пленки на монокристаллической подложке',
    isCorrect: false,
    questionId: 57,
  },
  {
    id: 257,
    title: 'поликристаллические пленки на аморфной подложке',
    isCorrect: false,
    questionId: 57,
  },
  {
    id: 258,
    title: 'поликристаллические пленки на поликристаллической подложке',
    isCorrect: false,
    questionId: 57,
  },
  {
    id: 259,
    title: 'хлоридный и силановый',
    isCorrect: true,
    questionId: 58,
  },
  {
    id: 260,
    title: 'силановый и фторидный',
    isCorrect: false,
    questionId: 58,
  },
  {
    id: 261,
    title: 'фторидный и хлоридный',
    isCorrect: false,
    questionId: 58,
  },
  {
    id: 262,
    title: 'фторидный и хлор-силановый',
    isCorrect: false,
    questionId: 58,
  },
  {
    id: 263,
    title: 'хлоридный и фторидный',
    isCorrect: false,
    questionId: 58,
  },
  {
    id: 264,
    title: 'горизонтальный, вертикальный, баррельный, индивидуальный',
    isCorrect: true,
    questionId: 59,
  },
  {
    id: 265,
    title: 'цилиндрический, круглый, прямоугольный, квадратный',
    isCorrect: false,
    questionId: 59,
  },
  {
    id: 266,
    title: 'баррельный, горизонтальный с кипящим слоем, вертикальный с соплом Лаваля',
    isCorrect: false,
    questionId: 59,
  },
  {
    id: 267,
    title: 'горизонтальный, вертикальный, поперечный, протяженный',
    isCorrect: false,
    questionId: 59,
  },
  {
    id: 268,
    title: 'горизонтальный, вертикальный, индивидуальный со сливом пограничного слоя',
    isCorrect: false,
    questionId: 59,
  },
  {
    id: 269,
    title: 'физического осаждения из эффузионных ячеек Кнутсена на горячую подложку',
    isCorrect: true,
    questionId: 60,
  },
  {
    id: 270,
    title: 'физического осаждения из пара на теплую подложку',
    isCorrect: false,
    questionId: 60,
  },
  {
    id: 271,
    title: 'химического осаждения из жидкости на горячую подложку',
    isCorrect: false,
    questionId: 60,
  },
  {
    id: 272,
    title: 'физического осаждения из пара на холодную подложку',
    isCorrect: false,
    questionId: 60,
  },
  {
    id: 273,
    title: 'химическое осаждение из парогазовой фазы',
    isCorrect: false,
    questionId: 60,
  },
  {
    id: 274,
    title: 'для обеспечения равномерности наращивания слоя кремния на всех подложках',
    isCorrect: true,
    questionId: 61,
  },
  {
    id: 275,
    title: 'для увеличения количество подложек',
    isCorrect: false,
    questionId: 61,
  },
  {
    id: 276,
    title: 'для ускорения обработки',
    isCorrect: false,
    questionId: 61,
  },
  {
    id: 277,
    title: 'для снижения дефектности',
    isCorrect: false,
    questionId: 61,
  },
  {
    id: 278,
    title: 'для исключения деформации подложек',
    isCorrect: false,
    questionId: 61,
  },
  {
    id: 279,
    title: 'выше скорость наращивания и меньше температура процесса',
    isCorrect: true,
    questionId: 62,
  },
  {
    id: 280,
    title: 'дешевле',
    isCorrect: false,
    questionId: 62,
  },
  {
    id: 281,
    title: 'безопаснее',
    isCorrect: false,
    questionId: 62,
  },
  {
    id: 282,
    title: 'более устойчив к внешним факторам воздействия',
    isCorrect: false,
    questionId: 62,
  },
  {
    id: 283,
    title: 'прост в использовании',
    isCorrect: false,
    questionId: 62,
  },
  {
    id: 284,
    title: 'с жидкометаллическим теплоносителем',
    isCorrect: true,
    questionId: 63,
  },
  {
    id: 285,
    title: 'баррельный',
    isCorrect: false,
    questionId: 63,
  },
  {
    id: 286,
    title: 'индивидуальной обработки',
    isCorrect: false,
    questionId: 63,
  },
  {
    id: 287,
    title: 'колоколообразный',
    isCorrect: false,
    questionId: 63,
  },
  {
    id: 288,
    title: 'горизонтальный',
    isCorrect: false,
    questionId: 63,
  },
  {
    id: 289,
    title: 'да, для обоих',
    isCorrect: true,
    questionId: 64,
  },
  {
    id: 290,
    title: 'нет, ни для какого',
    isCorrect: false,
    questionId: 64,
  },
  {
    id: 291,
    title: 'может только для КМОП',
    isCorrect: false,
    questionId: 64,
  },
  {
    id: 292,
    title: 'может только для биполярного транзистора',
    isCorrect: false,
    questionId: 64,
  },
  {
    id: 293,
    title: 'может только для МОП транзистора',
    isCorrect: false,
    questionId: 64,
  },
  {
    id: 294,
    title: 'при температуре больше 900°С',
    isCorrect: true,
    questionId: 65,
  },
  {
    id: 295,
    title: 'при температурах 550-900°С',
    isCorrect: false,
    questionId: 65,
  },
  {
    id: 296,
    title: 'при температурах меньше 550°С',
    isCorrect: false,
    questionId: 65,
  },
  {
    id: 297,
    title: 'при температуре в 1200°С',
    isCorrect: false,
    questionId: 65,
  },
  {
    id: 298,
    title: 'нейтрализации',
    isCorrect: true,
    questionId: 66,
  },
  {
    id: 299,
    title: 'для получения жидких реактивов',
    isCorrect: false,
    questionId: 66,
  },
  {
    id: 300,
    title: 'для получения газообразных реактивов',
    isCorrect: false,
    questionId: 66,
  },
  {
    id: 301,
    title: 'для ускорения процесса эпитаксии',
    isCorrect: false,
    questionId: 66,
  },
  {
    id: 302,
    title: 'для снижения дефектности',
    isCorrect: false,
    questionId: 66,
  },
  {
    id: 303,
    title: 'для окисления активных продуктов реакций и реагентов с целью их нейтрализации',
    isCorrect: true,
    questionId: 56,
  },
  {
    id: 304,
    title: 'для повышения скорости реакции',
    isCorrect: false,
    questionId: 56,
  },
  {
    id: 305,
    title: 'для снижения скорости реакции',
    isCorrect: false,
    questionId: 56,
  },
  {
    id: 306,
    title: 'для наращивания слоя оксида кремния',
    isCorrect: false,
    questionId: 56,
  },
  {
    id: 307,
    title: 'для активации процесса',
    isCorrect: false,
    questionId: 56,
  },
  // {
  //   id: 290,
  //   title: '',
  //   isCorrect: false,
  //   questionId: 65,
  // },
  // {
  //   id: 290,
  //   title: '',
  //   isCorrect: false,
  //   questionId: 65,
  // },
  // {
  //   id: 290,
  //   title: '',
  //   isCorrect: false,
  //   questionId: 65,
  // },
  // {
  //   id: 290,
  //   title: '',
  //   isCorrect: false,
  //   questionId: 65,
  // },
  // {
  //   id: 290,
  //   title: '',
  //   isCorrect: false,
  //   questionId: 65,
  // },
]
